name: aoc2021
version: 0.1.0.0
license: BSD3
author: Sascha Rechenberger
maintainer: sascha.rechenberger@uni-ulm.de
copyright: 2022 Sascha Rechenberger

synopsis: AoC 2022 solutions
category: Puzzle

dependencies:
  - base
  - containers
  - mtl
  - lens
  - parsec


default-extensions:
  - TypeFamilies
  - FlexibleContexts
  - FlexibleInstances
  - DeriveGeneric
  - ScopedTypeVariables
  - MultiParamTypeClasses
  - FunctionalDependencies
  - BinaryLiterals
  - TupleSections


executables:
  y2021d01part1:
    main: part1.hs
    source-dirs: "01" 
  y2021d01part2:
    main: part2.hs
    source-dirs: "01"
  
  y2021d02part1:
    main: part1.hs
    source-dirs: "02" 
  y2021d02part2:
    main: part2.hs
    source-dirs: "02" 
  
  y2021d03part1:
    main: part1.hs
    source-dirs: "03" 
  y2021d03part2:
    main: part2.hs
    source-dirs: "03" 
  
  y2021d04part1:
    main: part1.hs
    source-dirs: "04" 
  y2021d04part2:
    main: part2.hs
    source-dirs: "04" 