name: aoc2022
version: 0.1.0.0
author: Sascha Rechenberger
maintainer: sascha.rechenberger@uni-ulm.de
copyright: 2022 Sascha Rechenberger

synopsis: AoC 2022 solutions
category: Puzzle

dependencies:
  - base
  - containers
  - mtl
  - lens
  - parsec
  - regex-tdfa
#  - regex-tdfa-text


default-extensions:
  - TypeFamilies
  - FlexibleContexts
  - FlexibleInstances
  - DeriveGeneric
  - ScopedTypeVariables
  - MultiParamTypeClasses
  - FunctionalDependencies
  - BinaryLiterals
  - TupleSections


executables:
  y2022d01part1:
    main: part1.hs
    source-dirs: "01" 
  y2022d01part2:
    main: part2.hs
    source-dirs: "01"

  y2022d02part1:
    main: part1.hs
    source-dirs: "02" 
  y2022d02part2:
    main: part2.hs
    source-dirs: "02"

  y2022d03part1:
    main: part1.hs
    source-dirs: "03" 
  y2022d03part2:
    main: part2.hs
    source-dirs: "03"

  y2022d04part1:
    main: part1.hs
    source-dirs: "04" 
  y2022d04part2:
    main: part2.hs
    source-dirs: "04"

  y2022d05part1:
    main: part1.hs
    source-dirs: "05" 
  y2022d05part2:
    main: part2.hs
    source-dirs: "05"

  y2022d06part1:
    main: part1.hs
    source-dirs: "06" 
  y2022d06part2:
    main: part2.hs
    source-dirs: "06"

  y2022d07part1:
    main: part1.hs
    source-dirs: "07" 
  y2022d07part2:
    main: part2.hs
    source-dirs: "07"

  y2022d08part1:
    main: part1.hs
    source-dirs: "08" 
  y2022d08part2:
    main: part2.hs
    source-dirs: "08"

  y2022d09part1:
    main: part1.hs
    source-dirs: "09" 
  y2022d09part2:
    main: part2.hs
    source-dirs: "09"

  y2022d10part1:
    main: part1.hs
    source-dirs: "10" 
  y2022d10part2:
    main: part2.hs
    source-dirs: "10"

  y2022d11part1:
    main: part1.hs
    source-dirs: "11" 
  y2022d11part2:
    main: part2.hs
    source-dirs: "11"

  y2022d12part1:
    main: part1.hs
    source-dirs: "12" 
  y2022d12part2:
    main: part2.hs
    source-dirs: "12"
  
  y2022d13part1:
    main: part1.hs
    source-dirs: "13" 
  y2022d13part2:
    main: part2.hs
    source-dirs: "13"
  
  y2022d14part1:
    main: part1.hs
    source-dirs: "14" 
  y2022d14part2:
    main: part2.hs
    source-dirs: "14"
  
  y2022d15part1:
    main: part1.hs
    source-dirs: "15" 
  y2022d15part2:
    main: part2.hs
    source-dirs: "15"